# Generated by Django 6.0.5 on 2026-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Trainer', 'Trainer'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
